const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1512,height:1100},deviceScaleFactor:1});
 const errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:8790');
 await page.getByRole('heading',{name:'Connect your game'}).waitFor();
 await page.waitForFunction(()=>document.querySelectorAll('[data-group]').length===3);
 if(!await page.locator('#start').isDisabled()) throw new Error('Disconnected search must be disabled');
 if(await page.locator('#resources').inputValue()!=='state') throw new Error('Save-state resources must be default');
 await page.locator('#resources').selectOption('cap');
 if(!await page.locator('#stock-cap').isVisible()) throw new Error('Resource cap field failed');
 await page.locator('#reset-rules').click();
 if(await page.locator('#stock-cap').isVisible()) throw new Error('Reset did not clear cap');
 await page.locator('#future-game').click();
 if(!await page.locator('#game-wizard').isVisible()) throw new Error('Game adapter dialog failed');
 await page.locator('#wizard-close').click();
 await page.locator('#prepare').click();
 await page.waitForFunction(()=>document.querySelector('#script-path').value.endsWith('connect.lua'));
 const script=await page.locator('#script-path').inputValue();
 if(!fs.existsSync(script)) throw new Error('Session script was not generated');
 await page.locator('#connect-help').evaluate(el=>el.open=false);
 await page.locator('#dismiss-notice').click();
 await page.screenshot({path:'artifacts/ui/dashboard-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/ui/dashboard-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow) throw new Error('Mobile page has horizontal overflow');
 if(errors.length) throw new Error(errors.join('\n'));
 console.log(JSON.stringify({passed:true,checks:['disabled offline controls','state resource default','cap control','reset rules','game registry dialog','real session preparation','desktop screenshot','mobile screenshot','no mobile overflow','no JS exceptions'],sessionScript:script},null,2));
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
