const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(process.argv[2]);
  await page.locator('[data-game="vampire-savior"]').waitFor();
  await page.locator('#future-game').click();
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-error').filter({hasText:'Enter a game name'}).waitFor();
  await page.locator('#wg-title').fill('Wizard test game');
  await page.locator('#wg-id').fill('wizard-browser');
  await page.locator('#wg-rom').fill('testrom');
  await page.locator('#wg-health').fill('300');
  await page.locator('#wizard-next').click();
  await page.locator('#wg-LP-p1').waitFor();
  await page.locator('#wizard-close').click();
  await page.reload();await page.locator('[data-game="vampire-savior"]').waitFor();
  await page.locator('#future-game').click();
  await page.locator('#wg-LP-p1').waitFor();
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-error').filter({hasText:'valid address'}).waitFor();
  let address=4096;
  for(const player of ['p1','p2'])for(const name of ['health','x','stun1'])await page.locator(`#wg-${player}-${name}-address`).fill('0x'+(address+=2).toString(16));
  await page.setViewportSize({width:390,height:844});
  fs.mkdirSync('artifacts/ui',{recursive:true});
  await page.screenshot({path:'artifacts/ui/game-wizard-mobile.png'});
  if(await page.evaluate(()=>{const d=document.querySelector('#game-wizard');return d.scrollWidth>d.clientWidth+1||document.documentElement.scrollWidth>innerWidth}))throw Error('Mobile overflow');
  await page.locator('#wizard-next').click();
  await page.locator('[data-wsequence]').first().fill('HP');
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-error').filter({hasText:'unmapped'}).waitFor();
  await page.locator('[data-wsequence]').first().fill('LP');
  await page.locator('#wizard-next').click();
  await page.locator('#wg-calibrated').waitFor();
  if(await page.locator('#wg-calibrated').isChecked())throw Error('New game must start uncalibrated');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'artifacts/ui/game-wizard-review.png'});
  await page.locator('#wizard-next').click();
  await page.locator('#game-wizard').waitFor({state:'hidden'});
  await page.locator('[data-game="wizard-browser"]').waitFor();
  if(await page.locator('#true-combo').isChecked())throw Error('Uncalibrated game must not require a true combo');
  await page.locator('#edit-game-profile').click();
  await page.locator('#wg-title').fill('Edited wizard game');
  if(!await page.locator('#wg-id').isDisabled())throw Error('Editing must preserve stable ID');
  for(let i=0;i<4;i++)await page.locator('#wizard-next').click();
  await page.locator('#wg-calibrated').waitFor();await page.locator('#wizard-next').click();
  await page.locator('#game-wizard').waitFor({state:'hidden'});
  await page.reload();await page.getByRole('button',{name:'CG Edited wizard game'}).waitFor();
  if(errors.length)throw Error(errors.join('\n'));
  console.log('Wizard browser checks passed: validation, drafts, mobile layout, save, edit, reload, no JS errors.');
 } finally {await browser.close()}
})().catch(error=>{console.error(error);process.exit(1)});
